### ISSUE TITLE
Needs more UI and graphical elements

### ISSUE THREAD

**Issue by sqorbrody** [Amplify-Social/Amplify-Social.github.io#3]
I think we need more color and graphical elements?

**Comment by sqorandy** [comment]
Oh for certain.  This is purely in a build phase while I'm learning how to use jekyll.

**Comment by spudnic** [comment]
Cool  :)

On Tue, Jun 23, 2015 at 10:48 PM, sqorandy notifications@github.com wrote:

> Oh for certain. This is purely in a build phase while I'm learning how to
> use jekyll.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Amplify-Social/Amplify-Social.github.io/issues/3#issuecomment-114734452
> .

## 

Jason Brody-Stewart-Stroeh
